chats/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = "chats"

urlpatterns = [
    path("", views.DiscussionListView.as_view(), name="discussions"),
    path(
        "discussion/<slug>/",
        views.DiscussionDetailView.as_view(),
        name="discussion_detail",
    ),
    path(
        "discussion/<slug>/update",
        views.DiscussionUpdateView.as_view(),
        name="discussion_update",
    ),
    path(
        "discussion_create",
        views.DiscussionFormView.as_view(),
        name="discussion_create",
    ),
    path("trendings/", views.Trendings.as_view(), name="trendings"),
    path("invite_people/", views.InvitePeople.as_view(), name="invite_people"),
    path("room/<int:pk>/", views.RoomDetailView.as_view(), name="room"),
    path("thread/<str:pk>/", views.ThreadDetailView.as_view(), name="thread"),
    path("threads/", views.ThreadListView.as_view(), name="threads"),
    path("thread_new/", views.ThreadCreateView.as_view(), name="thread_new"),
    path("room_mutate/", views.RoomMutate.as_view(), name="room_mutate"),
    path("clear_history/", views.ClearHistory.as_view(), name="clear_history"),
    path("room_delete/<int:pk>/", views.RoomDeleteView.as_view(), name="room_delete"),
    path("search/", views.DiscussionSearchView.as_view(), name="search_room"),
    path("user_rooms/", views.UserRoomListView.as_view(), name="user_rooms"),
    path(
        "message_delete/<int:pk>/",
        views.MessageDeleteView.as_view(),
        name="message_delete",
    ),
    path(
        "total_unread_messages/",
        views.total_unread_messages,
        name="total_unread_messages",
    ),
]

chatter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views import defaults as default_views

admin.site.site_header = (
    "Dj-chat administration"  # change the default django admin title
)

urlpatterns = [
    path(
        "auth/", include("allauth.urls")
    ),  # basic user managements (login/logout, signup, change email/password)
    path(
        "select2/", include("django_select2.urls")
    ),  # Javascript select2 for multiple selects
    path("admin/", admin.site.urls),
]

# Custom app urls
urlpatterns += [
    path("", include("chats.urls", namespace="chats")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

chats/forms.py
from django import forms
from django.contrib.auth.views import get_user_model
from django.db import IntegrityError

from django_select2 import forms as s2forms

from .models import DiscussionRoom, Message
from .models import Tag


class TagWidget(s2forms.ModelSelect2TagWidget):
    search_fields = [
        "name__icontains",
    ]
    queryset = Tag.objects.all()

    def value_from_datadict(self, data, files, name):
        """Create objects for given non-pimary-key values. Return list of all primary keys."""
        values = list(super().value_from_datadict(data, files, name))
        val_int = []
        val_str = []
        for val in values:
            try:
                val_int.append(int(val))
            except:
                val_str.append(val)
        old_tags = list(
            self.queryset.filter(**{"pk__in": val_int}).values_list("pk", flat=True)
        )
        print("old_tags", old_tags)
        print("val_int", val_int)
        print("val_str", val_str)

        new_tags = []
        for val in val_str:
            new_tags.append(Tag(name=val))
        new_tags = self.queryset.bulk_create(new_tags, ignore_conflicts=True)

        # new_pks = [a.pk for a in new_tags]
        new_pks = [Tag.objects.get(name=t).id for t in new_tags]

        return new_pks + old_tags


class DiscussionRoomForm(forms.ModelForm):
    class Meta:
        model = DiscussionRoom
        # exclude = ['room', 'owner', 'members']
        fields = ["headline", "description", "tags"]
        widgets = {
            "headline": forms.TextInput(
                attrs={
                    "autocomplete": "off",
                }
            ),
            "description": forms.Textarea(
                attrs={
                    "rows": 4,
                }
            ),
            "tags": TagWidget,
        }


class RecipientWidget(s2forms.ModelSelect2MultipleWidget):
    search_fields = [
        "username__icontains",
        "first_name__icontains",
        "last_name__icontains",
    ]


class BulkMessageForm(forms.Form):
    # To whom do you want to send message
    recipients = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        label="To whom",
        widget=RecipientWidget,
    )
    message = forms.CharField(
        widget=forms.Textarea(attrs={"rows": 4, "placeholder": "Type your message..."})
    )


class InviteForm(forms.Form):
    users = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        label="Find peoples",
        help_text="Search by username or full name without including @",
        widget=RecipientWidget,
    )
    room = forms.ModelChoiceField(
        queryset=DiscussionRoom.objects.all(), widget=forms.HiddenInput()
    )

chats/views.py
from typing import Any, Dict, List, Optional
from django.db import models
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth import get_user_model
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.contrib import messages
from django.urls import reverse

from django.utils.safestring import mark_safe
from django.core.paginator import Paginator
from django.views.generic import (
    ListView,
    DetailView,
    FormView,
    UpdateView,
    DeleteView,
    CreateView,
    View,
)
import json

from .models import Message, Room, Thread, DiscussionRoom
from .forms import DiscussionRoomForm, BulkMessageForm, InviteForm


@method_decorator(login_required, name="dispatch")
class RoomDetailView(DetailView):
    context_object_name = "room"
    queryset = Room.objects.all()
    template_name = "chats/room.html"


@method_decorator(login_required, name="dispatch")
class DiscussionDetailView(DetailView):
    context_object_name = "room"
    queryset = DiscussionRoom.objects.all()
    template_name = "chats/discussion_detail.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        obj = self.get_object()
        ctx = super().get_context_data(**kwargs)
        ctx["room_name_json"] = mark_safe(json.dumps(obj.room.id))
        ctx["username"] = mark_safe(json.dumps(self.request.user.username))

        return ctx


@method_decorator(login_required, name="dispatch")
class DiscussionListView(ListView):
    context_object_name = "rooms"
    paginate_by = 16

    def get_queryset(self) -> QuerySet[Any]:
        queryset = DiscussionRoom.objects.all()
        sort = self.request.GET.get("sort")
        if sort == "newest":
            queryset = queryset.order_by("-created")
        elif sort == "oldest":
            queryset = queryset.order_by("created")
        else:
            sort = "trendings"
            queryset = DiscussionRoom.objects.get_trendings(qs=queryset)

        return queryset

    def get_template_names(self) -> List[str]:
        if self.request.htmx:
            return "chats/partials/discussions.html"
        return "chats/discussions.html"

    def get_paginate_by(self, queryset: QuerySet[Any]) -> int | None:
        paginate_by = self.request.GET.get("paginate_by")
        if paginate_by:
            return paginate_by
        return super().get_paginate_by(queryset)


@method_decorator(login_required, name="dispatch")
class UserRoomListView(ListView):
    context_object_name = "rooms"
    paginate_by = 10

    def get_queryset(self) -> QuerySet[Any]:
        queryset = DiscussionRoom.objects.filter(members=self.request.user).order_by(
            "room__updated"
        )
        return queryset

    def get_template_names(self) -> List[str]:
        if self.request.GET.get("display") == "modal" and self.request.GET.get(
            "paginat"
        ):
            return "chats/partials/user_rooms_popup_body.html"
        if self.request.GET.get("display") == "modal":
            return "chats/partials/user_rooms_popup.html"
        return "chats/partials/user_rooms.html"


@method_decorator(login_required, name="dispatch")
class Trendings(ListView):
    template_name = "chats/trendings.html"
    context_object_name = "discussions"
    paginate_by = 3

    def get_queryset(self) -> QuerySet[Any]:
        excludes = list(self.request.GET.get("exclude"))
        queryset = DiscussionRoom.objects.get_trendings(
            excludes=[int(e) for e in excludes]
        )
        return queryset


@method_decorator(login_required, name="dispatch")
class InvitePeople(FormView):
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        form = InviteForm(request.POST)
        users_pks = [int(pk) for pk in request.POST.getlist("users")]
        room_id = request.POST.get("room")
        d_room = get_object_or_404(DiscussionRoom, id=room_id)
        invitations = []
        User = get_user_model()
        usernames = [u.username for u in User.objects.filter(id__in=users_pks)]
        # for pk in users_pks:
        # 	invitations.append(CustomNotification(
        # 		type="invitation",
        # 		recipient=get_user_model().objects.get(id=pk),
        # 		actor=request.user,
        # 		verb=f'{request.user.get_name} sent you an invitation to join the discussion "{d_room.headline}"',
        # 		redirect_url=d_room.get_absolute_url
        # 	))
        # CustomNotification.objects.bulk_create(invitations)
        return HttpResponse(
            f"""
            <h5 class="text-success text-center">Invitation sent!</h5> 
            <p class="text-center">Your invitation has been sent to {[u for u in usernames]}</p>
            """
        )
        # return super().post(request, *args, **kwargs)

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        form = InviteForm(initial={"room": request.GET.get("room")})
        return render(request, "chats/invite.html", {"form": form})
        # return super().get(request, *args, **kwargs)


@method_decorator(login_required, name="dispatch")
class DiscussionFormView(FormView):
    form_class = DiscussionRoomForm

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        return super().post(request, *args, **kwargs)

    def form_valid(self, form: Any) -> HttpResponse:
        d_room = form.save(commit=False)
        d_room.owner = self.request.user
        room_obj = Room.objects.create()
        d_room.room = room_obj
        d_room.save()
        d_room.members.add(d_room.owner)
        tags = form.cleaned_data.get("tags")
        d_room.tags.set(tags)
        return redirect(d_room.get_absolute_url)
        # return super().form_valid(form)

    def get_template_names(self) -> List[str]:
        if self.request.htmx:
            return "chats/partials/discussion_room_form.html"
        return "chats/discussion_room_form.html"


@method_decorator(login_required, name="dispatch")
class DiscussionUpdateView(UpdateView):
    form_class = DiscussionRoomForm
    queryset = DiscussionRoom.objects.all()
    # lookup_expr = 'pk'

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        d_room = form.save()
        tags = form.cleaned_data.get("tags")
        d_room.tags.set(tags)
        return redirect(d_room.get_absolute_url)

    def get_template_names(self) -> List[str]:
        if self.request.htmx:
            return "chats/partials/discussion_room_form.html"
        return "chats/discussion_room_form.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        ctx["update"] = True
        return ctx


@method_decorator(login_required, name="dispatch")
class DiscussionSearchView(ListView):
    template_name = "chats/search_room.html"
    context_object_name = "rooms"

    def get_queryset(self) -> QuerySet[Any]:
        query = self.request.GET.get("q")
        return DiscussionRoom.objects.search(query)


@method_decorator(login_required, name="dispatch")
class ThreadListView(ListView):
    context_object_name = "rooms"

    def get_queryset(self) -> QuerySet[Any]:
        return Thread.objects.filter(
            Q(user1=self.request.user) | Q(user2=self.request.user)
        ).distinct()

    def get_template_names(self) -> List[str]:
        if self.request.htmx:
            return "chats/partials/threads_nav.html"
        return "chats/threads.html"


@method_decorator(login_required, name="dispatch")
class ThreadDetailView(DetailView):
    context_object_name = "thread"

    # def get_queryset(self) -> QuerySet[Any]:
    #     thread, created = Thread.objects.new_or_get(
    #         self.request.user, self.get_context_data["partner"]
    #     )
    #     return thread

    def get_object(self, queryset: QuerySet[Any] | None = ...):
        partner = get_object_or_404(get_user_model(), id=self.request.GET.get("pid"))
        thread, created = Thread.objects.new_or_get(self.request.user, partner)
        return thread

    def get_template_names(self) -> List[str]:
        if self.request.htmx and self.request.GET.get("display") == "popup":
            template_name = "chats/partials/thread_popup.html"
        elif self.request.htmx:
            template_name = "chats/partials/thread.html"
        else:
            template_name = "chats/thread_single.html"
        return template_name

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        thread = self.get_object()
        user = self.request.user
        ctx["partner"] = get_object_or_404(
            get_user_model(), id=self.request.GET.get("pid")
        )
        ctx["room"] = thread.room
        ctx["rooms"] = Thread.objects.filter(Q(user1=user) | Q(user2=user)).distinct()
        ctx["room_name_json"] = mark_safe(json.dumps(thread.room.id))
        ctx["username"] = mark_safe(json.dumps(user.username))

        return ctx


@method_decorator(login_required, name="dispatch")
class ThreadCreateView(FormView):
    form_class = BulkMessageForm
    template_name = "chats/thread_new.html"

    def form_valid(self, form):
        msg = form.cleaned_data.get("message")
        recipients = form.cleaned_data.get("recipients")
        msgs = []
        for user in recipients:
            thread, created = Thread.objects.new_or_get(self.request.user, user)
            message = Message.objects.create(
                author=self.request.user, room=thread.room, content=msg
            )
            msgs.append(message.id)
        names = [
            f'<span class="badge bg-dark me-1">{r.username}</span>' for r in recipients
        ]

templates/chats/discussions.html
{% extends '_base.html' %}

{% load static crispy_forms_tags %}

{% load django_htmx %}
{% django_htmx_script %}

{% block title %} Discussion Rooms | Dj-chat {% endblock %}

{% block content %}

<br>

<div class="d-md-none plus-area">
	<a role="button" class="btn btn-lg btn-primary shadow border" hx-get="{% url 'chats:discussion_create' %}"
		hx-target="#hx-modal" hx-indicator="#indicator"><i class="fa fa-plus"></i></a>
	<a role="button" class="btn btn-lg btn-light shadow border" hx-get="{% url 'chats:user_rooms' %}?display=modal"
		hx-target="#hx-modal" hx-indicator="#indicator"><i class="fa fa-history"></i>
		<span class="notify-badge" style="display: block;">
			<span id="">34</span>
			<span class="visually-hidden">unread notifications</span>
		</span></a>
</div>

<section>
	<div class="container">
		<div class="row align-items-top">
			<div class="col-md-4 d-none d-md-block">
				<div style="position: sticky; top: 70px;">
					<div class="card p-3 mb-2">
						<a href="{{ request.user.get_absolute_url }}" class="d-flex align-items-top mb-1">
							<div class="avatar avatar-text me-2">
								{{ request.user.username|first }}
							</div>
							<div class="publisher-detail text-dark">
								<h6 class="mb-0">{{ request.user.first_name }} {{ request.user.last_name }}</h6>
								<p class="mb-2 text-muted" style="font-size: 12px;">
									@{{ request.user.username }} - Last login: {{ request.user.last_login|date }}</p>
							</div>
						</a>
						<a role="button" class="btn btn-sm btn-primary" hx-get="{% url 'chats:discussion_create' %}"
							hx-target="#hx-modal" hx-indicator="#indicator">+ Create a New Room</a>
					</div>
					<div class="card p-3 mb-2">
						<h6>Recent Rooms</h6>
						<div class="" hx-get="{% url 'chats:user_rooms' %}" hx-trigger="load" hx-target="this"
							id="user-books-list">
							<span class="dots-loader">
								<i class="spinner__dot spinner__dot--one"></i>
								<i class="spinner__dot spinner__dot--two"></i>
								<i class="spinner__dot spinner__dot--three"></i>
							</span>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-8">

				<div class="d-flex justify-content-between align-items-center">
					<h4>Discussions</h4>
					<div class="dropdown">
						<a class="dropdown-toggle" href="#" id="sortOption" role="button" data-bs-toggle="dropdown"
							aria-expanded="false"></a>
						<ul class="dropdown-menu dropdown-menu-end" aria-labelledby="sortOption">
							<li><a class="sort-action dropdown-item" id="trendings" href="?sort=trendings"
									hx-get="?sort=trendings" hx-target="#roomsContainer>.row" hx-push-url="true"
									hx-indicator="#indicator">Trendings</a></li>
							<li><a class="sort-action dropdown-item" id="newest" href="?sort=newest"
									hx-get="?sort=newest" hx-target="#roomsContainer>.row" hx-push-url="true"
									hx-indicator="#indicator">Newest</a></li>
							<li><a class="sort-action dropdown-item" id="oldest" href="?sort=oldest"
									hx-get="?sort=oldest" hx-target="#roomsContainer>.row" hx-push-url="true"
									hx-indicator="#indicator">Oldest</a></li>
						</ul>
					</div>
				</div>

				<!-- room search box -->
				<div class="position-relative p-0 mb-3">
					<input class="form-control ps-5" type="search" name="q" placeholder="Search rooms..."
						aria-label="Search" hx-get="{% url 'chats:search_room' %}"
						hx-trigger="keyup changed delay:500ms" hx-target="#roomsContainer"
						hx-indicator="#rooms-filter-indicator" autocomplete="off">
					<i class="fa fa-search input-icon-left"></i>
					<input type="submit" hidden>
				</div>

				<div class="htmx-indicator static" id="rooms-filter-indicator">
					<span class="dots-loader mb-2">
						<i class="spinner__dot spinner__dot--one"></i>
						<i class="spinner__dot spinner__dot--two"></i>
						<i class="spinner__dot spinner__dot--three"></i>
					</span>
					<!-- <img src="{% static 'images/preloader-md.svg' %}" class="mb-3" width="40px"> -->
				</div>

				<div id="roomsContainer">
					<div class="row">
						{% for room in rooms %}
						{% include 'chats/partials/discussion_card.html' %}
						{% endfor %}
						{% if page_obj.has_next %}
						<div id="rooms-paginator">
							<a hx-get="{% url 'chats:discussions' %}?page={{ page_obj.next_page_number }}"
								hx-target="#rooms-paginator" hx-trigger="click" hx-swap="outerHTML" role="button"
								id="load-more" class="btn btn-sm border w-100 mt-3">
								Load More <i class="fa fa-circle-arrow-down"></i>
								<div class="htmx-indicator">
									<span class="dots-loader">
										<i class="spinner__dot spinner__dot--one"></i>
										<i class="spinner__dot spinner__dot--two"></i>
										<i class="spinner__dot spinner__dot--three"></i>
									</span>
								</div>
							</a>
						</div>
						{% endif %}
					</div>
					<!-- <button class="btn btn-outline-primary w-100" id="htmx-loader"
						hx-get="{% url 'chats:discussions' %}?page={{ page_number|add:'1' }}" hx-target="#roomsContainer>.row"
						hx-swap="beforeend">
						Load More Rooms...
					</button> -->
				</div>

			</div>
		</div>
	</div>
</section>

<br><br><br>

{% endblock %}

{% block newsletter %}{% endblock %}
{% block footer %}{% endblock %}

{% block script %}
<script>
	var sort = '{{ sort }}';

	// let next_page = parseInt({{ page_number }}) + 1;
	// let total_pages = {{ num_pages }};
	// let url = "{% url 'chats:discussions' %}?page=";

	$(document).ready(function () {
		$('.sort-action').on('click', function () {
			sort = $(this).attr('id');
			sortBtnAppearance();
		})
		function sortBtnAppearance() {
			$sortOption = $('#sortOption');
			$('.sort-action').removeClass('active');
			if (sort == 'newest') {
				$sortOption.html('⏱ Newest')
				$('#newest').addClass('active')
			}
			else if (sort == 'oldest') {
				$sortOption.html('⏳ oldest')
				$('#oldest').addClass('active')
			}
			else {
				$sortOption.html('🔥 Trendings')
				$('#trendings').addClass('active')
			}
		}
		sortBtnAppearance();
	})
</script>
{% endblock %}

templates/chats/invite.html
{% load static %}
{% load crispy_forms_tags %}

<div id="modal-backdrop" class="modal-backdrop fade show" style="display:block;"></div>
<div id="modal" class="modal fade show animated--grow-in" tabindex="-1" style="display:block;">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content radius-400 overflow-hidden border-0">

			<div class="modal-header px-3 py-2 border-0">
				<h5 class="modal-title"><i class="fa fa-user-plus"></i> Invite people</h5>
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"
					onclick="closeModal()"></button>
			</div>
			<div class="modal-body" id="id_invitation">

				{{ form.media.css }}
				<form action="{% url 'chats:invite_people' %}" method="POST">{% csrf_token %}
					{% for field in form %}
					<div class="mb-3">
						{{ field|as_crispy_field }}
					</div>
					{% endfor %}
					<input type="hidden" name="next" value="{{ next }}">
					<button hx-post="{% url 'chats:invite_people' %}" hx-target="#id_invitation" type="submit"
						class="btn btn-primary"><i class="fa fa-paper-plane"></i> Send Invitation</button>
				</form>
				{{ form.media.js }}

			</div>
			<!-- <div class="modal-footer">
			<a href="" class="small a-fb-default">
				<i class="fas fa-street-view fa-1x"></i> Nearby peoples
			</a>
		</div> -->
		</div>
	</div>
</div>

templates/chats/threads.html
{% extends '_base.html' %}
{% load static %}
{% load chats_extras %}

{% block title %}All Messages - Dj-chat{% endblock %}

{% block content %}
<script src="{% static 'js/chat.js' %}"></script>

<style>
	p {
		font-weight: 300 !important;
	}

	body {
		height: 100vh !important;
		max-height: 100vh !important;
		max-height: 100vh !important;
		overflow: hidden;
	}
</style>

<div class="container">
	<div class="row py-3">
		<div class="d-none d-lg-block col-lg-4 ms-auto scroller">

			<div class="chat-nav position-relative radius-400 border bg-light scroll-y scroller"
				style="height: 83vh; max-height: 83vh; z-index: 1;">

				<!-- head -->
				<header class="text-center border-bottom bg-light" style="position: sticky; top: 0; z-index: 1;">
					<div class="align-items-center d-flex px-4 py-2">
						<div>Messages</div>
						<div class="ms-auto">
							<a role="button" class="btn btn-sm btn-outline-primary ms-auto"
								hx-get="{% url 'chats:thread_new' %}?next={{ request.path }}" hx-target="#hx-modal">
								New message
								<div class="text-center htmx-indicator">
									<span class="dots-loader">
										<i class="spinner__dot spinner__dot--one"></i>
										<i class="spinner__dot spinner__dot--two"></i>
										<i class="spinner__dot spinner__dot--three"></i>
									</span>
								</div>
							</a>
						</div>
					</div>
				</header>

				<ul class="list-unstyled">
					{% for room in rooms %}
					{% get_partner request.user room as partner %}
					<li class="px-2 mt-1">
						<a role="button" class="py-3 px-2 mx-auto row w-100 text-dark chat-link"
							hx-get="{% url 'chats:thread' room.id %}?pid={{ partner.id }}" hx-target="#chat-area"
							hx-indicator="#room-indicator" hx-push-url="true">
							<div class="col-2 p-0">
								<div>
									<div class="avatar avatar-md avatar-text">
										{{ partner.username|first }}
									</div>
								</div>
							</div>
							<div class="col-10 position-relative">
								<h6 class="small mb-1 text-truncate">{{ partner.get_full_name|title }}</h6>
								<div class="small text-muted text-truncate">
									{% if room.room.latest_message.author == request.user %}
									<span class="text-success">You:</span>
									{% endif %}
									{{ room.room.latest_message.content }}
								</div>
								<div class="position-absolute text-dark px-2 radius-400"
									style="background-color: #85cdca; top: 50%; right: 0; transform: translate(-50%, -50%);">
									{{ unread_messages }}</div>
							</div>
						</a>
					</li>
					{% empty %}
					<div class="my-5 text-center">
						<i class="far fa-meh-blank text-muted fa-3x mb-1"></i>
						<p>So Empty</p>
						<a role="button" class="btn btn-sm btn-primary rounded-pill ms-auto"
							hx-get="{% url 'chats:thread_new' %}?next={{ request.path }}" hx-target="#hx-modal">
							Start New Message
							<div class="text-center htmx-indicator">
								<span class="dots-loader">
									<i class="spinner__dot spinner__dot--one"></i>
									<i class="spinner__dot spinner__dot--two"></i>
									<i class="spinner__dot spinner__dot--three"></i>
								</span>
							</div>
						</a>
					</div>
					{% endfor %}
				</ul>

				<div class="fade-top p-4" style="position: sticky; bottom: 0;"></div>
			</div>

		</div>
		<div class="col-lg-6 d-none d-lg-flex me-auto d-flex" style="height: 83vh; max-height: 83vh;">
			<div id="room-indicator" class="htmx-indicator animated--fade-down"
				style="width: 60px; height: 60px; top: 0; left: 50%; margin-left: -30px; z-index: 110;">
				<img src="{% static 'images/preloader-md.svg' %}" width="40px" class="radius-200"
					style="box-shadow: 0 0 15px 2px rgba(0,0,0,.1);" alt="Loading..." />
			</div>
			<div id="chat-area" class="d-flex radius-400 border bg-white w-100">
				<h6 class="mx-auto my-auto small">Select a chat to start messaging</h6>
			</div>
		</div>
	</div>
</div>

{% endblock %}

{% block newsletter %}{% endblock %}
{% block footer %}{% endblock %}

{% block script %}
<script>
	$('.chat-link').click(function () {
		$('.chat-link.active').removeClass('active');
		$(this).addClass('active');
		history.pushState({ tab: 'message room' }, '', this.href);
	})
</script>
{% endblock %}

templates/chats/trendings.html
{% for room in discussions %}
<a href="{{ room.get_absolute_url }}" class="text-dark">
	<div class="card border bg-light mb-2 p-2 small">
		{{ room.headline }}: {{ room.description|truncatechars:50 }}
	</div>
</a>
{% endfor %}