chats/urls.py
# chat/urls.py
from django.urls import path

from . import views

app_name = "chats"

urlpatterns = [
    path("", views.DiscussionListView.as_view(), name="discussions"),
    path(
        "discussion/<slug>/",
        views.DiscussionDetailView.as_view(),
        name="discussion_detail",
    ),
    path(
        "discussion/<slug>/update",
        views.DiscussionUpdateView.as_view(),
        name="discussion_update",
    ),
    path(
        "discussion_create",
        views.DiscussionFormView.as_view(),
        name="discussion_create",
    ),
    path("trendings/", views.Trendings.as_view(), name="trendings"),
    path("invite_people/", views.InvitePeople.as_view(), name="invite_people"),
    path("room/<int:pk>/", views.RoomDetailView.as_view(), name="room"),
    path("thread/<str:pk>/", views.ThreadDetailView.as_view(), name="thread"),
    path("threads/", views.ThreadListView.as_view(), name="threads"),
    path("thread_new/", views.ThreadCreateView.as_view(), name="thread_new"),
    path("room_mutate/", views.RoomMutate.as_view(), name="room_mutate"),
    path("clear_history/", views.ClearHistory.as_view(), name="clear_history"),
    path("room_delete/<int:pk>/", views.RoomDeleteView.as_view(), name="room_delete"),
    path("search/", views.DiscussionSearchView.as_view(), name="search_room"),
    path("user_rooms/", views.UserRoomListView.as_view(), name="user_rooms"),
    path(
        "message_delete/<int:pk>/",
        views.MessageDeleteView.as_view(),
        name="message_delete",
    ),
    path(
        "total_unread_messages/",
        views.total_unread_messages,
        name="total_unread_messages",
    ),
]

chatter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views import defaults as default_views

admin.site.site_header = (
    "Dj-chat administration"  # change the default django admin title
)

urlpatterns = [
    path(
        "auth/", include("allauth.urls")
    ),  # basic user managements (login/logout, signup, change email/password)
    path(
        "select2/", include("django_select2.urls")
    ),  # Javascript select2 for multiple selects
    path("admin/", admin.site.urls),
]

# Custom app urls
urlpatterns += [
    path("", include("chats.urls", namespace="chats")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]

chats/forms.py
from django import forms
from django.contrib.auth.views import get_user_model
from django.db import IntegrityError

from django_select2 import forms as s2forms

from .models import DiscussionRoom, Message
from .models import Tag


class TagWidget(s2forms.ModelSelect2TagWidget):
    search_fields = [
        "name__icontains",
    ]
    queryset = Tag.objects.all()

    def value_from_datadict(self, data, files, name):
        """Create objects for given non-pimary-key values. Return list of all primary keys."""
        values = list(super().value_from_datadict(data, files, name))
        val_int = []
        val_str = []
        for val in values:
            try:
                val_int.append(int(val))
            except:
                val_str.append(val)
        old_tags = list(
            self.queryset.filter(**{"pk__in": val_int}).values_list("pk", flat=True)
        )
        print("old_tags", old_tags)
        print("val_int", val_int)
        print("val_str", val_str)

        new_tags = []
        for val in val_str:
            new_tags.append(Tag(name=val))
        new_tags = self.queryset.bulk_create(new_tags, ignore_conflicts=True)

        # new_pks = [a.pk for a in new_tags]
        new_pks = [Tag.objects.get(name=t).id for t in new_tags]

        return new_pks + old_tags


class DiscussionRoomForm(forms.ModelForm):
    class Meta:
        model = DiscussionRoom
        # exclude = ['room', 'owner', 'members']
        fields = ["headline", "description", "tags"]
        widgets = {
            "headline": forms.TextInput(
                attrs={
                    "autocomplete": "off",
                }
            ),
            "description": forms.Textarea(
                attrs={
                    "rows": 4,
                }
            ),
            "tags": TagWidget,
        }


class RecipientWidget(s2forms.ModelSelect2MultipleWidget):
    search_fields = [
        "username__icontains",
        "first_name__icontains",
        "last_name__icontains",
    ]


class BulkMessageForm(forms.Form):
    # To whom do you want to send message
    recipients = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        label="To whom",
        widget=RecipientWidget,
    )
    message = forms.CharField(
        widget=forms.Textarea(attrs={"rows": 4, "placeholder": "Type your message..."})
    )


class InviteForm(forms.Form):
    users = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        label="Find peoples",
        help_text="Search by username or full name without including @",
        widget=RecipientWidget,
    )
    room = forms.ModelChoiceField(
        queryset=DiscussionRoom.objects.all(), widget=forms.HiddenInput()
    )

chats/views.py
from typing import Any, Dict, List, Optional
from django.db import models
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth import get_user_model
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpRequest, HttpResponse, JsonResponse
from django.contrib import messages
from django.urls import reverse

from django.utils.safestring import mark_safe
from django.core.paginator import Paginator
from django.views.generic import (
    ListView,
    DetailView,
    FormView,
    UpdateView,
    DeleteView,
    CreateView,
    View,
)
import json

from .models import Message, Room, Thread, DiscussionRoom
from .forms import DiscussionRoomForm, BulkMessageForm, InviteForm


@method_decorator(login_required, name="dispatch")
class RoomDetailView(DetailView):
    context_object_name = "room"
    queryset = Room.objects.all()
    template_name = "chats/room.html"


@method_decorator(login_required, name="dispatch")
class DiscussionDetailView(DetailView):
    context_object_name = "room"
    queryset = DiscussionRoom.objects.all()
    template_name = "chats/discussion_detail.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        obj = self.get_object()
        ctx = super().get_context_data(**kwargs)
        ctx["room_name_json"] = mark_safe(json.dumps(obj.room.id))
        ctx["username"] = mark_safe(json.dumps(self.request.user.username))

        return ctx


@method_decorator(login_required, name="dispatch")
class DiscussionListView(ListView):
    context_object_name = "rooms"
    paginate_by = 16

    def get_queryset(self) -> QuerySet[Any]:
        queryset = DiscussionRoom.objects.all()
        sort = self.request.GET.get("sort")
        if sort == "newest":
            queryset = queryset.order_by("-created")
        elif sort == "oldest":
            queryset = queryset.order_by("created")
        else:
            sort = "trendings"
            queryset = DiscussionRoom.objects.get_trendings(qs=queryset)

        return queryset

    def get_template_names(self) -> List[str]:
        if self.request.htmx:
            return "chats/partials/discussions.html"
        return "chats/discussions.html"

    def get_paginate_by(self, queryset: QuerySet[Any]) -> int | None:
        paginate_by = self.request.GET.get("paginate_by")
        if paginate_by:
            return paginate_by
        return super().get_paginate_by(queryset)


@method_decorator(login_required, name="dispatch")
class UserRoomListView(ListView):
    context_object_name = "rooms"
    paginate_by = 10

    def get_queryset(self) -> QuerySet[Any]:
        queryset = DiscussionRoom.objects.filter(members=self.request.user).order_by(
            "room__updated"
        )
        return queryset

    def get_template_names(self) -> List[str]:
        if self.request.GET.get("display") == "modal" and self.request.GET.get(
            "paginat"
        ):
            return "chats/partials/user_rooms_popup_body.html"
        if self.request.GET.get("display") == "modal":
            return "chats/partials/user_rooms_popup.html"
        return "chats/partials/user_rooms.html"


@method_decorator(login_required, name="dispatch")
class Trendings(ListView):
    template_name = "chats/trendings.html"
    context_object_name = "discussions"
    paginate_by = 3

    def get_queryset(self) -> QuerySet[Any]:
        excludes = list(self.request.GET.get("exclude"))
        queryset = DiscussionRoom.objects.get_trendings(
            excludes=[int(e) for e in excludes]
        )
        return queryset


@method_decorator(login_required, name="dispatch")
class InvitePeople(FormView):
    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        form = InviteForm(request.POST)
        users_pks = [int(pk) for pk in request.POST.getlist("users")]
        room_id = request.POST.get("room")
        d_room = get_object_or_404(DiscussionRoom, id=room_id)
        invitations = []
        User = get_user_model()
        usernames = [u.username for u in User.objects.filter(id__in=users_pks)]
        # for pk in users_pks:
        # 	invitations.append(CustomNotification(
        # 		type="invitation",
        # 		recipient=get_user_model().objects.get(id=pk),
        # 		actor=request.user,
        # 		verb=f'{request.user.get_name} sent you an invitation to join the discussion "{d_room.headline}"',
        # 		redirect_url=d_room.get_absolute_url
        # 	))
        # CustomNotification.objects.bulk_create(invitations)
        return HttpResponse(
            f"""
            <h5 class="text-success text-center">Invitation sent!</h5> 
            <p class="text-center">Your invitation has been sent to {[u for u in usernames]}</p>
            """
        )
        # return super().post(request, *args, **kwargs)

    def get(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        form = InviteForm(initial={"room": request.GET.get("room")})
        return render(request, "chats/invite.html", {"form": form})
        # return super().get(request, *args, **kwargs)


@method_decorator(login_required, name="dispatch")
class DiscussionFormView(FormView):
    form_class = DiscussionRoomForm

    def post(self, request: HttpRequest, *args: str, **kwargs: Any) -> HttpResponse:
        return super().post(request, *args, **kwargs)

    def form_valid(self, form: Any) -> HttpResponse:
        d_room = form.save(commit=False)
        d_room.owner = self.request.user
        room_obj = Room.objects.create()
        d_room.room = room_obj
        d_room.save()
        d_room.members.add(d_room.owner)
        tags = form.cleaned_data.get("tags")
        d_room.tags.set(tags)
        return redirect(d_room.get_absolute_url)
        # return super().form_valid(form)

    def get_template_names(self) -> List[str]:
        if self.request.htmx:
            return "chats/partials/discussion_room_form.html"
        return "chats/discussion_room_form.html"


@method_decorator(login_required, name="dispatch")
class DiscussionUpdateView(UpdateView):
    form_class = DiscussionRoomForm
    queryset = DiscussionRoom.objects.all()
    # lookup_expr = 'pk'

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        d_room = form.save()
        tags = form.cleaned_data.get("tags")
        d_room.tags.set(tags)
        return redirect(d_room.get_absolute_url)

    def get_template_names(self) -> List[str]:
        if self.request.htmx:
            return "chats/partials/discussion_room_form.html"
        return "chats/discussion_room_form.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        ctx["update"] = True
        return ctx


@method_decorator(login_required, name="dispatch")
class DiscussionSearchView(ListView):
    template_name = "chats/search_room.html"
    context_object_name = "rooms"

    def get_queryset(self) -> QuerySet[Any]:
        query = self.request.GET.get("q")
        return DiscussionRoom.objects.search(query)


@method_decorator(login_required, name="dispatch")
class ThreadListView(ListView):
    context_object_name = "rooms"

    def get_queryset(self) -> QuerySet[Any]:
        return Thread.objects.filter(
            Q(user1=self.request.user) | Q(user2=self.request.user)
        ).distinct()

    def get_template_names(self) -> List[str]:
        if self.request.htmx:
            return "chats/partials/threads_nav.html"
        return "chats/threads.html"


@method_decorator(login_required, name="dispatch")
class ThreadDetailView(DetailView):
    context_object_name = "thread"

    # def get_queryset(self) -> QuerySet[Any]:
    #     thread, created = Thread.objects.new_or_get(
    #         self.request.user, self.get_context_data["partner"]
    #     )
    #     return thread

    def get_object(self, queryset: QuerySet[Any] | None = ...):
        partner = get_object_or_404(get_user_model(), id=self.request.GET.get("pid"))
        thread, created = Thread.objects.new_or_get(self.request.user, partner)
        return thread

    def get_template_names(self) -> List[str]:
        if self.request.htmx and self.request.GET.get("display") == "popup":
            template_name = "chats/partials/thread_popup.html"
        elif self.request.htmx:
            template_name = "chats/partials/thread.html"
        else:
            template_name = "chats/thread_single.html"
        return template_name

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        ctx = super().get_context_data(**kwargs)
        thread = self.get_object()
        user = self.request.user
        ctx["partner"] = get_object_or_404(
            get_user_model(), id=self.request.GET.get("pid")
        )
        ctx["room"] = thread.room
        ctx["rooms"] = Thread.objects.filter(Q(user1=user) | Q(user2=user)).distinct()
        ctx["room_name_json"] = mark_safe(json.dumps(thread.room.id))
        ctx["username"] = mark_safe(json.dumps(user.username))

        return ctx


@method_decorator(login_required, name="dispatch")
class ThreadCreateView(FormView):
    form_class = BulkMessageForm
    template_name = "chats/thread_new.html"

    def form_valid(self, form):
        msg = form.cleaned_data.get("message")
        recipients = form.cleaned_data.get("recipients")
        msgs = []
        for user in recipients:
            thread, created = Thread.objects.new_or_get(self.request.user, user)
            message = Message.objects.create(
                author=self.request.user, room=thread.room, content=msg
            )
            msgs.append(message.id)
        names = [
            f'<span class="badge bg-dark me-1">{r.username}</span>' for r in recipients
        ]

templates/chats/partials/chat_delete.html
{% load static %}

<div id="modal-backdrop" class="modal-backdrop fade show" style="display:block;"></div>
<div id="modal" class="modal fade show animated--grow-in" tabindex="-1" style="display:block;">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content radius-400 overflow-hidden border-0">
			<div class="modal-header border-0">
				Are you sure?
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"
					onclick="closeModal()"></button>
			</div>
			<div class="modal-body text-center">
				<p>This will <b>delete</b> the chat permanently and it cannot be <b>undone!</b></p>
				<div class="d-flex justify-content-center">
					<button type="button" class="btn btn-light border me-2" data-bs-dismiss="modal" aria-label="Close"
						onclick="closeModal()">Cancle</button>
					<form action="{% url 'chats:room_delete' room.id %}" method="POST">
						{% csrf_token %}
						<button type="submit" class="btn btn-danger">Delete chat</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

templates/chats/partials/chat_delete_popup.html
{% load static %}

<div id="modal-backdrop" class="modal-backdrop fade show" style="display:block;"></div>
<div id="modal" class="modal fade show animated--grow-in" tabindex="-1" style="display:block;">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content radius-400 overflow-hidden border-0">
			<div class="modal-header p-3 border-0">
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"
					onclick="closeModal()"></button>
			</div>
			<div class="modal-body text-center">
				<h5>Are you sure?</h5>
				<p>This will delete the chat permanently and it cannot be <strong>undone!</strong></p>
				<div class="d-flex justify-content-center">
					<button type="button" class="btn btn-light border me-2" data-bs-dismiss="modal" aria-label="Close"
						onclick="closeModal()">Cancle</button>
					<form action="{% url 'chats:chat_delete' room.id %}" method="POST">
						{% csrf_token %}
						<button type="submit" class="btn btn-danger">Delete chat</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

templates/chats/partials/clear_history.html
{% load static %}

<div id="modal-backdrop" class="modal-backdrop fade show" style="display:block;"></div>
<div id="modal" class="modal fade show animated--grow-in" tabindex="-1" style="display:block;">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content radius-400 overflow-hidden border-0">
			<div class="modal-header border-0">
				Are you sure?
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"
					onclick="closeModal()"></button>
			</div>
			<div class="modal-body text-center">
				<p>This will <b>clear</b> everything in this chat permanently and it cannot be <b>undone!</b></p>
				<div class="d-flex justify-content-center">
					<button type="button" class="btn btn-light border me-2" data-bs-dismiss="modal" aria-label="Close"
						onclick="closeModal()">Cancle</button>
					<form action="{% url 'chats:clear_history' %}" method="POST">
						{% csrf_token %}
						<input type="hidden" name="room_id" value="{{ room_id }}">
						<input type="hidden" name="partner_id" value="{{ partner_id }}">
						<button type="submit" class="btn btn-danger">Clear history</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

templates/chats/partials/discussion_card.html
<div class="col-md-6 mb-2">
	<a href="{{ room.get_absolute_url }}" class="text-dark">
		<div class="card h-100 p-3 link-card position-relative">
			<div href="#" class="d-flex align-items-top mb-1">
				<div class="avatar avatar-text me-2">
					{{ room.owner.username|first }}
				</div>
				<div>
					<p class="small lh-1 m-0 text-dark">{{ room.owner.first_name }} {{ room.owner.last_name }}</p>
					<p class="small lh-1 mb-2 text-muted">@{{ room.owner.username }}</p>
				</div>
			</div>
			<div class="mb-3">
				<b>{{ room.headline }}:</b>
				<span class="small">{{ room.description|truncatechars:230 }}</span>
			</div>
			<div class="d-flex flex-wrap mt-auto">
				{% for tag in room.tags.all %}
				<span class="bg-success-200 small rounded-pill px-2 me-1 mb-1">{{ tag }}</span>
				{% endfor %}
			</div>
			<div class="d-flex justify-content-between align-items-center mt-auto">
				<small class="text-muted">{{ room.created|date }}</small>
				<div class="avatar-group">
					<div class="hidden-avatars">{{ room.get_messages.count }}+</div>
					{% for member in room.room.snip_room_members %}
					<div class="avatar avatar-text">
						{{ member.username|first }}
					</div>
					{% endfor %}
				</div>
			</div>
		</div>
	</a>
</div>

templates/chats/partials/discussions.html
{% for room in rooms %}
{% include 'chats/partials/discussion_card.html' %}
{% endfor %}

{% if page_obj.has_next %}
<div id="rooms-paginator">
	<a hx-get="{% url 'chats:discussions' %}?page={{ page_obj.next_page_number }}" hx-target="#rooms-paginator"
		hx-trigger="click" hx-swap="outerHTML" role="button" id="load-more" class="btn btn-sm border w-100 mt-3">
		Load More <i class="fa fa-circle-arrow-down"></i>
		<div class="htmx-indicator">
			<span class="dots-loader">
				<i class="spinner__dot spinner__dot--one"></i>
				<i class="spinner__dot spinner__dot--two"></i>
				<i class="spinner__dot spinner__dot--three"></i>
			</span>
		</div>
	</a>
</div>
{% endif %}

templates/chats/partials/message_delete.html
{% load static %}

<div id="modal-backdrop" class="modal-backdrop fade show" style="display:block;"></div>
<div id="modal" class="modal fade show animated--grow-in" tabindex="-1" style="display:block;">
	<div class="modal-dialog modal-dialog-centered">
		<div class="modal-content radius-400 overflow-hidden border-0">
			<div class="modal-header p-3 border-0">
				<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"
					onclick="closeModal()"></button>
			</div>
			<div class="modal-body text-center">
				<h5>Are you sure?</h5>
				<p>This will delete the message from both side.</p>
				<div class="d-flex justify-content-center">
					<button type="button" class="btn btn-light border me-2" data-bs-dismiss="modal" aria-label="Close"
						onclick="closeModal()">Cancle</button>
					<form action="{% url 'chats:message_delete' message.id %}" method="POST">
						{% csrf_token %}
						<input type="hidden" name="message_id" value="{{ message.id }}">
						<button type="submit" class="btn btn-danger">Delete message</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

templates/chats/partials/thread.html
<div class="chat-wrapper scroller bg-white w-100 justify-content-between d-flex flex-column position-relative">

	<div id="room-indicator" class="htmx-indicator"></div>

	<div class="chat-head px-3 py-2 bg-light-green d-flex justify-content-between align-items-center">
		<div class="d-flex align-items-center text-dark me-3">
			<div class="avatar avatar-text">
				{{ partner.username|first }}
			</div>
			<div class="ms-2 small mb-0 p-0 text-truncate">{{ partner.get_full_name|title }}</div>
		</div>

		<!-- room actions -->
		<div class="ms-auto dropdown">
			<button class="btn btn-sm btn-circle btn-outline-dark" type="button" id="chatMenu" data-bs-toggle="dropdown"
				data-bs-auto-close="outside" aria-expanded="false">
				<i class="fa fa-ellipsis"></i>
			</button>
			<ul class="dropdown-menu dropdown-menu-end" aria-labelledby="chatMenu">
				<li>
					<form action="{% url 'chats:room_mutate' %}?pid={{ partner.id }}" method="POST">
						{% csrf_token %}
						<input type="hidden" name="room_id" value="{{ room.id }}">
						<button hx-post="{% url 'chats:room_mutate' %}?pid={{ partner.id }}" hx-target="this"
							type="submit" class="dropdown-item small py-2">
							{% if room.muted %} Unmute {% else %} Mute notifications {% endif %}</button>
					</form>
				</li>
				<li>
					<button type="submit" class="dropdown-item small text-danger py-2"
						hx-get="{% url 'chats:clear_history' %}?room_id={{ room.id }}&partner_id={{ partner.id }}"
						hx-target="#hx-modal" hx-indicator="#room-indicator">Clear history</button>
				</li>
				<li>
					<button class="delete-chat dropdown-item small text-danger py-2" hx-target="#hx-modal"
						hx-get="{% url 'chats:room_delete' room.id %}" hx-indicator="#room-indicator">Delete
						Chat</button>
				</li>
			</ul>
		</div>

	</div>
	<div class="chat-body px-3 pb-2 pt-3">
		<ul id="chat-log" class="mt-auto p-0"></ul>
	</div>
	<div class="chat-footer d-flex align-items-center py-2 px-3 border-top">
		<div>
			<button type="button" class="btn btn-light btn-circle me-3">
				<i class="fa fa-face-angry"></i>
			</button>
		</div>
		<textarea name="message" id="chat-message-input" class="form-control" placeholder="Write a message..."
			rows="1"></textarea>
		<div>
			<button type="button" class="btn btn-sm bg-gray-400 ms-3" id="chat-message-submit" disabled>
				<i class="zmdi zmdi-mail-send fa-1-5x"></i>
			</button>
		</div>
	</div>
</div>

<script>
	roomName = {{ room_name_json }};
	username = {{ username }};
	roomId = {{ room.id }};
	// next = '{{ next_page }}';
	msg_counter_url = "{% url 'chats:total_unread_messages' %}";

	$().chat(roomName, username, roomId, msg_counter_url);
</script>

templates/chats/partials/threads_nav.html
{% load static %}
{% load chats_extras %}

{% for room in rooms %}

{% get_partner current_user=request.user room=room as partner %}
{% is_unread msg=room.room.latest_message user=request.user as unread %}
{% unread_count room=room.room user=request.user as count %}

<li>
	<a class="dropdown-item position-relative
	{% if unread == True %} unread {% endif %}" href="{% url 'chats:thread' room.id %}?pid={{ partner.id }}">
		{% if count > 0 %}
		<span class="notify-badge" style="display: block;">
			<span>{{ count }}</span>
			<span class="visually-hidden">unread message</span>
		</span>
		{% endif %}
		<div class="row">
			<div class="col-2 position-relative px-0">
				<div class="avatar avatar-md avatar-text">
					{{ partner.username|first }}
				</div>
				<div class="status-indicator bg-success"></div>
			</div>
			<div class="col-10">
				<div class="small text-truncate">{{ room.room.latest_message.content }}</div>
				<div class="x-small text-truncate text-gray-500">
					@{{ partner.username }} · {{ room.room.latest_message.created|timesince }}
				</div>
			</div>
		</div>
	</a>
</li>

{% empty %}
<div class="rounded-pill text-center p-2 bg-gray-200 my-4">Your messages will appear here</div>
{% endfor %}
<!-- {% if rooms.count >= 6 %}
<a class="dropdown-item text-center small p-2 bg-white text-primary" 
	href="{% url 'chats:threads' %}">Read More Messages</a>
{% endif %} -->

templates/chats/partials/user_rooms.html
{% load static %}

{% for room in rooms %}
<div class="mb-2">
	<a href="{{ room.get_absolute_url }}" class="d-inline-flex position-relative bg-light border radius-200 p-2">
		<p class="small mb-0">
			<b>{{ room.headline }}:</b>
			{{ room.description|truncatewords:6 }}
		</p>
		<!-- <span class="notify-badge" style="display: block;">
				<span id="">34</span>
				<span class="visually-hidden">unread notifications</span>
			</span> -->
	</a>
</div>
{% empty %}
<div class="d-flex flex-column justify-content-center align-items-center">
	<img src="{% static 'images/empty-folder.png' %}" width="70px">
	<h6 class="text-muted text-center mt-2">Nothing to show here.</h6>
</div>
{% endfor %}

{% if page_obj.has_next %}
<div id="user-room-paginator">
	<a hx-get="{% url 'chats:user_rooms' %}?page={{ page_obj.next_page_number }}" hx-target="#user-room-paginator"
		hx-trigger="click" hx-swap="outerHTML" role="button" id="load-more" class="btn btn-sm border w-100 mt-3">
		Load More <i class="fa fa-circle-arrow-down"></i>
		<div class="htmx-indicator">
			<span class="dots-loader">
				<i class="spinner__dot spinner__dot--one"></i>
				<i class="spinner__dot spinner__dot--two"></i>
				<i class="spinner__dot spinner__dot--three"></i>
			</span>
		</div>
	</a>
</div>
{% endif %}